# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: changelog-check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-changelog-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v -o _changelog ./cmd
    - name: Upload linter binary
      uses: actions/upload-artifact@v3
      with:
        name: changelog-check-binary
        path: _changelog
  run-changelog-check:
    runs-on: ubuntu-latest
    needs: build-changelog-check

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Download changelog check binary
        uses: actions/download-artifact@v3
        with:
          name: changelog-check-binary

      - name: Run lint command
        run: chmod +x _changelog && ./_changelog check -repo=$GITHUB_WORKSPACE -main-rev=origin/main

